apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  namespace: p2
  labels:
    app: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: paulbouwer/hello-kubernetes:1.10
          ports:
          - containerPort: 8080
          env:
          - name: MESSAGE
            value: "Hello from app1."
          - name: KUBERNETES_NAMESPACE
            value: "default namespace"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: p2
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two
          image: paulbouwer/hello-kubernetes:1.10
          ports:
          - containerPort: 8080
          env:
          - name: MESSAGE
            value: "Hello from app2."
          - name: KUBERNETES_NAMESPACE
            value: "default namespace"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  namespace: p2
  labels:
    app: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
        - name: app-three
          image: paulbouwer/hello-kubernetes:1.10
          ports:
          - containerPort: 8080
          env:
          - name: MESSAGE
            value: "Hello from app3."
          - name: KUBERNETES_NAMESPACE
            value: "default namespace"
